version: '3.4'
services:
  db:
    image: docker-from-zero-to-mastery-dotnet-mysql-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker_from_zero_to_mastery_dotnet
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  docker-from-zero-to-mastery-dotnet:  
    image: docker-from-zero-to-mastery-dotnet
    build:
      context: .
      dockerfile: DockerFromZeroToMastery/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:80"      
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge
